BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Link] (
    [id] INT NOT NULL IDENTITY(1,1),
    [url] NVARCHAR(1000) NOT NULL,
    [title] NVARCHAR(1000) NOT NULL,
    [description] NVARCHAR(1000),
    [aiSummary] NVARCHAR(1000),
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Link_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [Link_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
